### ISSUE TITLE
Zero values at T0

### ISSUE THREAD

**Issue by ADvorkinGheva** [hart-lab/bagel#24]
Greetings,

I am working with data obtained from shRNA screens performed using Affymetrix arrays. I am trying to prepare the file containing LogFC between T2 and T0; however, I have cases in which the value at T0 = 0. What should I do with these cases?

Thank you very much!

Regards,
Anna

**Comment by rooeikim** [comment]
Hi Anna,

Thank you for using BAGEL2.
If your screen contains zero values in the ctrl sample, you can give pseudo-values or discard them.

BAGEL fc options
--min-reads=N                            Discard gRNA with T0 counts < N (default 0)
-Np, --pseudo-count=N	     Add a pseudocount of N to every readcount (default 5)

Best,
Eiru Kim

**Comment by ADvorkinGheva** [comment]
Hi Eiru,

Thank you very much!

Regards,
Anna
