### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ADvorkinGheva** [hart-lab/bagel#25]
Greetings,

I've installed Bagel and tried to run the example; however, I have received the following error message:

```
python run_bagel_crisprcleanr.py -i HAP1-TKOv3-EXAMPLE.txt -s HAP1-TKOv3-EXAMPLE-SCREENINFO.txt -o HAP1-TKOv3-bagel
  File "run_bagel_crisprcleanr.py", line 218
    print(f"\n{filenames_rep.loc[rep,'ccr_fc']} doesn't exist. Skipped!\n")
                                                                         ^
SyntaxError: invalid syntax

```

I have checked and the Python I am running is 2.7, so this case does not seem to be the same as the Issue #1 .

Thank you!

Regards,
ANna

**Comment by rooeikim** [comment]
Hi Anna, 

BAGEL2 was tested in python 3 and the syntax is not supported in python 2. 
Since the python 2 version has been depreciated in 2019, so we decided to not support the legacy version.
We apologize for it. 

Best,
Eiru Kim.

**Comment by ADvorkinGheva** [comment]
Hi Eiru,

Thank you! I have switched to Python 3 and now everything seems to be running without any error messages. 

Regards,
Anna
