### ISSUE TITLE
What if there are multiple replicates for control condition?

### ISSUE THREAD

**Issue by rraadd88** [hart-lab/bagel#3]
Hi,
I was trying to analyse a CRISPR screen data with multiple replicates of control condition. I have 4 replicates of control conditions (and 4 for treated/test condition). So I was using this command:
```
python BAGEL.py fc -i {path to input} -o {path to output} -c 1,2,3,4
```
Then I got this error 
```
Traceback (most recent call last):
  File "BAGEL.py", line 165, in <module>
    ctrl_column = int(arg)
ValueError: invalid literal for int() with base 10: '1,2,3,4'
```
It seems to me that `bagel` (in the current version) is not applicable to data with multiple replicates of control condition. Please correct me if I am wrong.
Thank you. (`bagel` works very well if there is only one control condition.)

**Comment by rraadd88** [comment]
Hi again,
What if I analyse the 4 replicates of control conditions and 4 replicates for treated/test condition in a paired manner. i.e. 
```
1st control vs 1st test condition
1st control vs 1st test condition
1st control vs 1st test condition
```
then aggre

**Comment by rooeikim** [comment]
Hi rraadd88,

You can use 4 replicates when you use updated version of BAGEL. It is on the branch of this github. build_111

Thank you.

**Comment by rraadd88** [comment]
Hi @rooeikim ,
Thank you very much for the reply. `build_111` branch indeed supports multiple controls.
I find `bagel` very useful in CRISPR screens. Great work!
Thanks again.
