### ISSUE TITLE
Calculating F-measure (BF = 5), which is the harmonic mean of precision and recall at Bayes factor 5.

### ISSUE THREAD

**Issue by rraadd88** [hart-lab/bagel#4]
Hi @rooeikim and @traverhart,
I have been using `bagel` for few days. It works very well. After calculating the precision recall for the demo data (using `BAGEL.py pr`), I was trying to calculate F-measure and then looking forward to check the quality of the data based on the F-measure (>0.85). 

According to the description in the [Life Science Alliance paper](http://www.life-science-alliance.org/content/2/2/e201800278), 
> F-measure (BF = 5) is the harmonic mean of precision and recall at Bayes factor 5. 

I tried to see if there are any values of precision and recall at BF = 5. But it gave me empty dataframe. :/ (`dpr` below is the analysed demo data `hap1-t18.pr`).
![image](https://user-images.githubusercontent.com/9945034/56462423-d4508d00-6390-11e9-9b34-40e9ffff4907.png)

Any help regarding the calculation of the F-measure from the precision-recall data (output of `BAGEL.py pr`) would be highly appreciated.

**Comment by rooeikim** [comment]
I used to calculate F-measure(BF=5) using the values the closest but above than 5.0.

**Comment by rooeikim** [comment]
try below. 
dpr[dpr['BF']>5].sort_values('BF',ascending=False).tail(1)

**Comment by rraadd88** [comment]
Thank you very much for the reply @rooeikim .
That gave me one value of 'Precision' and 'Recall' each : 
![image](https://user-images.githubusercontent.com/9945034/56595179-2e816600-65bc-11e9-98bd-4b2ff56520ea.png)

So, next, harmonic mean of the two values should give me the F-measure, right?
e.g.
```
import scipy as sc
sc.stats.hmean(dpr[dpr['BF']>5].sort_values('BF',ascending=False).tail(1).iloc[0,1:])
```
Thanks again.
